version: 2.1

orbs:
  node: circleci/node@4.7.0
  gcp-gcr: circleci/gcp-gcr@0.13.0
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
  deploy_cloud_run:
    machine:
      # Docker Layer Caching
      docker_layer_caching: true
      # Resource Class
      resource_class: large
    steps:
      - checkout
      - gcp-cloud-run/init
      - gcp-gcr/build-image:
          image: first-circleci-demo
          tag: '${CIRCLE_SHA1}'
          registry-url: asia.gcr.io
      - gcp-cloud-run/deploy:
          image: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/first-circleci-demo:${CIRCLE_SHA1}'
          platform: managed
          region: asia-northeast1
          service-name: first-circleci-demo
          unauthenticated: true

workflows:
  test_and_deploy: 
    jobs:
      - node/test:
          run-command: test:ci
      - deploy_cloud_run:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
