version: 2.1

orbs:
  node: circleci/node@4.1
  cloudrun: circleci/gcp-cloud-run@1.0.2
  docker: circleci/docker@1.6.0

jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests
          command: yarn test

  build:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - docker/publish:
          deploy: false
          image: gcr.io/${GOOGLE_PROJECT_ID}/first-circleci-demo-${CIRCLE_SHA1}

workflows:
  sample: 
    jobs:
      - test
      - build
