version: 2.1

orbs:
  node: circleci/node@4.1
  cloudrun: circleci/gcp-cloud-run@1.0.2
  gcp-gcr: circleci/gcp-gcr@0.13.0

executors:
  executor-for-docker-build:
    docker:
      - image: cimg/base:2021.05

jobs:
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - run:
          name: Run tests
          command: yarn test

workflows:
  sample: 
    jobs:
      - test
      - gcp-gcr/build-and-push-image:
          executor: executor-for-docker-build
          image: first-circleci-demo-${CIRCLE_SHA1}
          registry-url: asia.gcr.io
          setup-remote-docker: true
          use-docker-layer-caching: true
