version: 2.1

orbs:
  node: circleci/node@4.7.0
  gcp-gcr: circleci/gcp-gcr@0.13.0
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2
  cypress: cypress-io/cypress@1.29.0

jobs:
  deploy_cloud_run:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - gcp-cloud-run/init
      - gcp-cloud-run/deploy:
          image: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/first-circleci-demo:${CIRCLE_SHA1}'
          platform: managed
          region: asia-northeast1
          service-name: first-circleci-demo
          unauthenticated: true

workflows:
  test_and_deploy: 
    jobs:
      - node/test:
          run-command: test:ci
      - cypress/run:
          store_artifacts: true
          start: npm run start
          wait-on: 'http://localhost:3000'
      - gcp-gcr/build-and-push-image:
          image: first-circleci-demo
          tag: '${CIRCLE_SHA1}'
          registry-url: asia.gcr.io
          use-docker-layer-caching: true
          requires:
            - cypress/run
            - node/test
          filters:
            branches:
              only:
                - master
      - deploy_cloud_run:
          requires:
            - gcp-gcr/build-and-push-image
