version: 2.1

orbs:
  node: circleci/node@4.7.0
  gcp-gcr: circleci/gcp-gcr@0.13.0

jobs:
  deploy_cloud_run:
    machine:
      # Docker Layer Caching
      docker_layer_caching: true
      # Resource Class
      resource_class: large
    steps:
      - checkout
      - gcp-gcr/gcr-auth
      - gcp-gcr/build-image:
          image: first-circleci-demo
          tag: '${CIRCLE_SHA1}'
          registry-url: asia.gcr.io
      - gcp-gcr/push-image:
          image: first-circleci-demo
          tag: '${CIRCLE_SHA1}'
          registry-url: asia.gcr.io
      - run:
          name: Deploy to Google Cloud run
          command: >-
            gcloud run deploy first-circleci-demo
            --platform=managed --region=asia-northeast1 --allow-unauthenticated
            --image=asia.gcr.io/${GOOGLE_PROJECT_ID}/first-circleci-demo:${CIRCLE_SHA1}

workflows:
  test_and_deploy: 
    jobs:
      - node/test:
          run-command: test:ci
          test-results-path: junit.xml # Upload Test Results
      - deploy_cloud_run:
          requires:
            - node/test
          filters:
            branches:
              only:
                - master
