version: 2.1

orbs:
  node: circleci/node@4.1
  gcp-gcr: circleci/gcp-gcr@0.13.0
  gcp-cloud-run: circleci/gcp-cloud-run@1.0.2

jobs:
  install_dependencies:
    docker:
      - image: cimg/node:15.1
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: yarn 
      - persist_to_workspace:
          root: .
          paths:
            - .
  
  test:
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: .
      - run: yarn test

  build:
    docker:
      - image: cimg/node:15.1
    steps:
      - attach_workspace:
          at: .
      - run: yarn build  

  deploy_cloud_run:
    docker:
      - image: 'cimg/base:stable'
    steps:
      - checkout
      - gcp-cloud-run/init
      - gcp-cloud-run/deploy:
          image: 'asia.gcr.io/${GOOGLE_PROJECT_ID}/first-circleci-demo:${CIRCLE_SHA1}'
          platform: managed
          region: asia-northeast1
          service-name: first-circleci-demo
          unauthenticated: true

workflows:
  build_and_test: 
    jobs:
      - install_dependencies
      - test:
          requires:
            - install_dependencies
      - build:
          requires:
            - install_dependencies

  docker_build_and_deploy_cloud_run:
    jobs:
      - gcp-gcr/build-and-push-image:
          image: first-circleci-demo
          tag: '${CIRCLE_SHA1}'
          registry-url: asia.gcr.io
          use-docker-layer-caching: true
          filters:
            branches:
              only:
                - master
      - deploy_cloud_run:
          requires:
            - gcp-gcr/build-and-push-image
